# This is a basic workflow to help you get started with Actions

name: stage & preview workflow

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ dev-cli ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  publish_dev_build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-versions: [ '3.8','3.9','3.10' ]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-versions }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions poetry

      - name: test with tox
        continue-on-error: true
        run:
          # tox
          ls
          
      
      - name: Create project version
        run: |
          POETRY_VERSION=$(poetry version --short).dev.$GITHUB_RUN_NUMBER
          echo $POETRY_VERSION

          TAG=$(git rev-parse --short=4 HEAD)
          echo $TAG

          PROJECT_VERSION=$POETRY_VERSION'.'$TAG
          echo $PROJECT_VERSION
          echo "PROJECT_VERSION=$PROJECT_VERSION" >> $GITHUB_ENV
      
      - name: Build wheels and source tarball
        run: |
          poetry version $PROJECT_VERSION
          poetry build

      - name: publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_TOKEN}}
          # repository_url: https://test.pypi.org/legacy/
          repository_url: https://upload.pypi.org/legacy/
          skip_existing: true
      

      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Github Actions job result
          to: ${{secrets.MAIL_TOUSERNAME}}
          from: suizhihao 
          body: Build and publish job of ${{github.repository}} completed successfully! ${{steps.git_log.outputs.log}}
